# Generated by Django 5.2 on 2026-01-25 19:34

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=accounts.models.generaste_code, max_length=15, unique=True, verbose_name='code')),
                ('code_used', models.BooleanField(default=False, verbose_name='code used')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='profile image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Office', 'Office'), ('Acadmyy', 'Acadmy'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='type')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses_city', to='settings.city', verbose_name='city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses_country', to='settings.country', verbose_name='country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user address',
                'verbose_name_plural': 'user addresses',
            },
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Office', 'Office'), ('Acadmyy', 'Acadmy'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone_numbers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user phone number',
                'verbose_name_plural': 'user phone numbers',
            },
        ),
    ]
