# Generated by Django 5.2 on 2026-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False, unique=True, verbose_name='code used'),
        ),
    ]
