# Generated by Django 5.2 on 2026-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False, verbose_name='code used'),
        ),
    ]
