# Generated by Django 5.2 on 2026-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_code_used'),
        ('products', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='favoured_by', to='products.product', verbose_name='favourite products'),
        ),
    ]
