# Generated by Django 5.2 on 2026-02-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='country name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='country code')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='home title')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='home subtitle')),
                ('banner_image', models.ImageField(upload_to='home_banners/', verbose_name='banner image')),
                ('activate', models.BooleanField(default=True, verbose_name='activate')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='facebook_link')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='twitter_link')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='linkedin_link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='instagram_link')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='settings.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='settings.country', verbose_name='country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
