# Generated by Django 5.2 on 2026-01-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='facebook_link')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='twitter_link')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='linkedin_link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='instagram_link')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='settings.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
