# Generated by Django 5.2 on 2026-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='home title')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='home subtitle')),
                ('banner_image', models.ImageField(upload_to='home_banners/', verbose_name='banner image')),
                ('activate', models.BooleanField(default=True, verbose_name='activate')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
    ]
