# Generated by Django 5.2 on 2026-01-25 07:48

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Featured', 'Featured')], max_length=50, verbose_name='flag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.generaste_code, max_length=15, unique=True, verbose_name='SKU'),
        ),
    ]
