# Generated by Django 5.2 on 2026-01-26 18:33

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_flag_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.generaste_code, max_length=15, verbose_name='SKU'),
        ),
    ]
