# Generated by Django 5.2 on 2026-01-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_review_user_name_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
